apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T07:13:33Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "3450"
  uid: 8cbaacd9-1fb7-45ae-bdf5-1f2d696a7a23
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.103.53.0
  clusterIPs:
  - 10.103.53.0
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31848
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
